name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm test
