name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['12', '14', '16']
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - run: npm test

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.8'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - run: npm run lint
